global using System.Collections.Immutable;
global using System.Text;
global using cryptobank.api.db;
global using cryptobank.api.errors;
global using Enhanced.DependencyInjection;
global using FastEndpoints;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using ProblemDetails = Microsoft.AspNetCore.Mvc.ProblemDetails;