global using System.Collections.Immutable;
global using System.Text;
global using cryptobank.api.db;
global using cryptobank.api.errors;
global using cryptobank.api.errors.exceptions;
global using cryptobank.api.utils.environment;
global using Enhanced.DependencyInjection;
global using FastEndpoints;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using SecurityException = cryptobank.api.errors.exceptions.SecurityException;
global using ValidationException = cryptobank.api.errors.exceptions.ValidationException;
global using ProblemDetails = Microsoft.AspNetCore.Mvc.ProblemDetails;